DROP SEQUENCE SQ_NOTICE;
CREATE SEQUENCE SQ_NOTICE START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_BOARD;
CREATE SEQUENCE SQ_BOARD START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_GUESTBOOK;
CREATE SEQUENCE SQ_GUESTBOOK START WITH 1 INCREMENT BY 1;


DROP TABLE TB_NOTICE CASCADE CONSTRAINT;
DROP TABLE TB_BOARD CASCADE CONSTRAINT;
DROP TABLE TB_GUESTBOOK CASCADE CONSTRAINT;



CREATE TABLE TB_NOTICE
(
    ID         NUMBER NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(255),
    USER_NAME   VARCHAR2(255),
    CONTENT     VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);


CREATE TABLE TB_BOARD
(
    NO         NUMBER NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(255),
    USER_NAME   VARCHAR2(255),
    CONTENT     VARCHAR2(255),
    VIEW_CNT    NUMBER DEFAULT 0,
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

CREATE TABLE TB_GUESTBOOK
(
    ID         NUMBER NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(255),
    USER_NAME   VARCHAR2(255),
    CONTENT     VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);





