-- Table , 시퀀스 등 구조 정의

DROP SEQUENCE SQ_BOARD_USER;
CREATE SEQUENCE SQ_BOARD_USER START WITH 1 INCREMENT BY 1;

DROP TABLE BOARD_USER CASCADE CONSTRAINT;

CREATE TABLE BOARD_USER
(
    USER_ID       NUMBER(5) NOT NULL
        CONSTRAINT PK_BOARD_USER PRIMARY KEY,
    NAME          VARCHAR2(30),
    EMAIL         VARCHAR2(300) UNIQUE,
    PASSWORD      VARCHAR2(300),
    DESCRIPT      VARCHAR2(300),
    FILE_URL          VARCHAR2(300),
    ROLE          VARCHAR2(20),
    INSERT_TIME   VARCHAR2(255),
    UPDATE_TIME   VARCHAR2(255),
    DELETE_YN     VARCHAR2(3),
    DELETE_TIME   VARCHAR2(255)
);

COMMIT;