INSERT INTO TB_NOTICE VALUES (1, '테스트 제목1', '테스트 내용 1', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), null);
INSERT INTO TB_NOTICE VALUES (2, '테스트 제목2', '테스트 내용 2', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), null);
INSERT INTO TB_NOTICE VALUES (3, '테스트 제목3', '테스트 내용 3', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), null);
INSERT INTO TB_NOTICE VALUES (4, '테스트 제목4', '테스트 내용 4', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), null);

COMMIT ;