DROP TABLE TB_NOTICE CASCADE CONSTRAINT;

CREATE TABLE TB_NOTICE(
    NO NUMBER NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(255),
    CONTENT VARCHAR2(255),
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255)
);